// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHoJKeSozMhTGuXDSoPwt9b7sgHc-z0zE',
    appId: '1:647843157506:web:db44bc6d8a8f07092af91b',
    messagingSenderId: '647843157506',
    projectId: 'shoppieecomerc',
    authDomain: 'shoppieecomerc.firebaseapp.com',
    storageBucket: 'shoppieecomerc.appspot.com',
    measurementId: 'G-MP26Q5CF97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlVREhJAaJeRVqKOkkEIQQfYkMR4lYhI',
    appId: '1:647843157506:android:ecc3ef11d86ceb082af91b',
    messagingSenderId: '647843157506',
    projectId: 'shoppieecomerc',
    storageBucket: 'shoppieecomerc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyi3E_Et3_uiwyxCjFXVe_DVfV_osgwII',
    appId: '1:647843157506:ios:53d31205787c30da2af91b',
    messagingSenderId: '647843157506',
    projectId: 'shoppieecomerc',
    storageBucket: 'shoppieecomerc.appspot.com',
    androidClientId: '647843157506-0ftf33opj6isfkj7k3b8gvd0bl88qcql.apps.googleusercontent.com',
    iosClientId: '647843157506-r5mvplr4hgk7l5s3je14oa55qn6un32u.apps.googleusercontent.com',
    iosBundleId: 'com.edugaon.shoppie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyi3E_Et3_uiwyxCjFXVe_DVfV_osgwII',
    appId: '1:647843157506:ios:99b9d882d1a140c72af91b',
    messagingSenderId: '647843157506',
    projectId: 'shoppieecomerc',
    storageBucket: 'shoppieecomerc.appspot.com',
    androidClientId: '647843157506-0ftf33opj6isfkj7k3b8gvd0bl88qcql.apps.googleusercontent.com',
    iosClientId: '647843157506-kmh5lk216676rq865g8nua7g4i0buf67.apps.googleusercontent.com',
    iosBundleId: 'com.edugaon.shoppie.RunnerTests',
  );
}
